services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: jimgas_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - jimgas_network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: jimgas_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - jimgas_network
    depends_on:
      - app

  db:
    image: mariadb:10.11
    container_name: jimgas_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: jimgas_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - jimgas_network

networks:
  jimgas_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
